# Cloud Build using Artifact Registry
# gcloud builds submit --config cloudbuild.ar.yaml --substitutions=_TAG=ci-$(date +%Y%m%d%H%M%S)

substitutions:
  _REGION: 'europe-west3'
  _REPO: 'apps'
  _SERVICE_NAME: 'ra-autohaus-tracker'
  _TAG: 'ci-${SHORT_SHA}'
  _ENVIRONMENT: 'production'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:${_TAG}'
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:${_TAG}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:${_TAG}'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--set-env-vars=ENVIRONMENT=${_ENVIRONMENT},PROJECT_ID=$PROJECT_ID,REGION=${_REGION},SERVICE_NAME=${_SERVICE_NAME},GCP_PROJECT_ID=$PROJECT_ID'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:${_TAG}'

options:
  logging: CLOUD_LOGGING_ONLY
